### ISSUE TITLE
Docker for OS/platform = linux/arm ?

### ISSUE THREAD

**Issue by juergenkellermann** [ronaldlangeveld/isplogger_server#5]
Hi Ronald, why I try to follow your instructions, I get this error:

docker: Error response from daemon: image with reference ronaldl93/isp-logger was found but does not match the specified platform: wanted linux/arm, actual: linux/amd64.

Do you plan to release a docker image tagged linux/arm aswell so I can run your image on my Raspberry Pi 4?

Cheers, Juergen.

**Comment by LouDou** [comment]
See here, same issue: https://github.com/ronaldlangeveld/isplogger_server/issues/4
